language: node_js
node_js:
- stable
cache: npm
before_script:
  - npm run build
  - npm link
script: jmsh --help
before_deploy:
  - npm run pkg
deploy:
  - provider: releases
    api_key:
      secure: n9YIclpl3Lnt+mXKYowYOGZTiHEGcQJw/GyeDZrxv6uIJmXqNPLP0FpS7vKqZKGCIwF6sTKufXjo3IN02tzM4EzEvi2WVZoJQKwGw/qAPfk7dFozQoe+m2AboFLj3RkWgeKnMEvTZZsFitg4PikYLOPSK1LUrA+YqgZrSlQ5M2s9AlV19dd7in9On0whtRNuD8waQpGFTJVYXHiAJbs93i223ReAMujZYxbKW0nw4nvIPsnGGJON4Ii7KAcG687nOE/99Fl5nXic9Obi9ORINKDKKdatNm5mu0kwtAiD/hnv8+B4ly7Xy1qNkfMDtZSauf5Pv1N51LxchwdFUu3BMuWOoUSCZJgQdAt3DGg9Pu8m+D4ApyxChv38vxubGKqVOaTXI6N9P6gKuTCbhBN5TRXL3K/pAe5D1OkbRJpM/22b6rTHPr5kz7ngRoXkf/oBH3SEsb6zwJd11xcLNL5E7a7jUTZGS9cUC3hAQX/IgGt7s9HkXdcze2CBDk0B6l7L2DkCbgiBc62mHdE2i1LA2QwoC6z8FpYmP+CYyW3dgbtHrB6yoCfTiknLUHMjXH/qpb6wT9Zdsj/Xe98ChIQ/pFiMxabgNlsZjWv8KF3IjrPJmnLCDqbQ39Y887gpKVlLMvQMkHgpTD45ppJ+yQbcBzbAYWtPCdGaE2aAP2fTf+g=
    file_glob: true
    file: bin/*
    skip_cleanup: true
    on:
      tags: true
      repo: living42/jmsh

  - provider: npm
    email: qzeqing@gmail.com
    api_key:
      secure: H77O1kF9brn2ywX7wrKoIurI6Y2EyMX3hUkWJmbA4gkYHoAWzv1EczKPVP+zNnczekLXwFgCDN6T4+ail5gKNjTCvvRD55r7fz81+CJGmf69aunhK6jr9YrcY1PwROh0hAohuQskX1vw8PdjlhWsl5+Wp5CHo6WzLcolfk9VdSii7BM5PabefpC0J1gnUgwdQiKxaeP8Ce4spMEE2ZBlWrKPjdkPGLvrFU67STMstzCISmWgA0C9VGmob+ZVkZEjhI4Ag1kCmmsiKOB/ajWM4sgjSTXKY73ol5BP7JBcaFcG5ePANeI4jBVlEWb1yKXaDJqoqoYdbvVIrNA2VEgth/E+WKiIdW9GTrIPMpXeMe+he7MlLmg6jnNjIZSDQLKCdwq1yoxC/olgzvbDHr2KBEdbFIM7Uroa+kEl/pu8gJqL/53V6U2NG8Zr2HG8OkAV2p4NSoib5oMCN7VXM0JdHjY/WUw1qxH8v5IyDGfXg3Zpin1IN3XvRvQu5oc1cAOoEXFRQcsEmoybogYQRyVckeafRLKDYE+Zfjq75t2ATMyAdZoM1CadplOALLdCxo7cRNMql/o9YqVeR9xqtHhjOFoFnM6eBqqFVW2MB2aH8+J4SvPnC7izY4Y6p0vFIGYr2OBDe6yGC5FxZ51J/6G2lQxyCe/RWlKlVIyXIaT+7L0=
    skip_cleanup: true
    on:
      tags: true
      repo: living42/jmsh
