name: Build

on:
  push:
    branches: [ master ]
    tags:
      - "v*"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: npm ci
    - run: npm run build
    - run: npm run pkg
    - run: npm link
    - run: jmsh --help

    - if: contains(github.ref, 'tags')
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}

    - if: contains(github.ref, 'tags')
      uses: marvinpinto/action-automatic-releases@v1.1.0
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          bin/*
